require("lazy").setup({
	"sainnhe/everforest",
	"VonHeikemen/lsp-zero.nvim",
	'neovim/nvim-lspconfig',
  	'hrsh7th/cmp-nvim-lsp',
	'hrsh7th/nvim-cmp',
	"L3MON4D3/LuaSnip",
	"saadparwaiz1/cmp_luasnip",
	'hrsh7th/cmp-nvim-lsp',
	'hrsh7th/cmp-buffer',
	'hrsh7th/cmp-path',
	"HealsCOdes/vim-gas",
	"bergercookie/asm-lsp"
})
